module Text.OpenGL.Properties where

-- | List of the commands that can appear between a Begin/End pair.
-- This list is from http://www.opengl.org/sdk/docs/man/xhtml/glBegin.xml.
-- The beginend (and associated allow-inside value) property in gl.spec
-- is not given for all of them, hence this list.
-- The glBegin.xml is quite old. This list should be updated with the
-- latest specifications.
-- TODO distinguish between commands that are *allowed* between Begin/End
-- and commands that can happen *only* between Begin/End.
allowedInBeginEnd:: [String]
allowedInBeginEnd =
  [
  -- generate GL_INVALID_OPERATION if called between Begin/End.

    "Vertex2s"
  , "Vertex2i"
  , "Vertex2f"
  , "Vertex2d"
  , "Vertex3s"
  , "Vertex3i"
  , "Vertex3f"
  , "Vertex3d"
  , "Vertex4s"
  , "Vertex4i"
  , "Vertex4f"
  , "Vertex4d"
  , "Vertex2sv"
  , "Vertex2iv"
  , "Vertex2fv"
  , "Vertex2dv"
  , "Vertex3sv"
  , "Vertex3iv"
  , "Vertex3fv"
  , "Vertex3dv"
  , "Vertex4sv"
  , "Vertex4iv"
  , "Vertex4fv"
  , "Vertex4dv"

  , "Color3b"
  , "Color3s"
  , "Color3i"
  , "Color3f"
  , "Color3d"
  , "Color3ub"
  , "Color3us"
  , "Color3ui"
  , "Color4b"
  , "Color4s"
  , "Color4i"
  , "Color4f"
  , "Color4d"
  , "Color4ub"
  , "Color4us"
  , "Color4ui"
  , "Color3bv"
  , "Color3sv"
  , "Color3iv"
  , "Color3fv"
  , "Color3dv"
  , "Color3ubv"
  , "Color3usv"
  , "Color3uiv"
  , "Color4bv"
  , "Color4sv"
  , "Color4iv"
  , "Color4fv"
  , "Color4dv"
  , "Color4ubv"
  , "Color4usv"
  , "Color4uiv"

  , "SecondaryColor3b"
  , "SecondaryColor3s"
  , "SecondaryColor3i"
  , "SecondaryColor3f"
  , "SecondaryColor3d"
  , "SecondaryColor3ub"
  , "SecondaryColor3us"
  , "SecondaryColor3ui"
  , "SecondaryColor3bv"
  , "SecondaryColor3sv"
  , "SecondaryColor3iv"
  , "SecondaryColor3fv"
  , "SecondaryColor3dv"
  , "SecondaryColor3ubv"
  , "SecondaryColor3usv"
  , "SecondaryColor3uiv"

  , "Indexs"
  , "Indexi"
  , "Indexf"
  , "Indexd"
  , "Indexub"
  , "Indexsv"
  , "Indexiv"
  , "Indexfv"
  , "Indexdv"
  , "Indexubv"

  , "Normal3b"
  , "Normal3d"
  , "Normal3f"
  , "Normal3i"
  , "Normal3s"
  , "Normal3bv"
  , "Normal3dv"
  , "Normal3fv"
  , "Normal3iv"
  , "Normal3sv"

  , "FogCoordd"
  , "FogCoordf"
  , "FogCoorddv"
  , "FogCoordfv"

  , "TexCoord1s"
  , "TexCoord1i"
  , "TexCoord1f"
  , "TexCoord1d"
  , "TexCoord2s"
  , "TexCoord2i"
  , "TexCoord2f"
  , "TexCoord2d"
  , "TexCoord3s"
  , "TexCoord3i"
  , "TexCoord3f"
  , "TexCoord3d"
  , "TexCoord4s"
  , "TexCoord4i"
  , "TexCoord4f"
  , "TexCoord4d"
  , "TexCoord1sv"
  , "TexCoord1iv"
  , "TexCoord1fv"
  , "TexCoord1dv"
  , "TexCoord2sv"
  , "TexCoord2iv"
  , "TexCoord2fv"
  , "TexCoord2dv"
  , "TexCoord3sv"
  , "TexCoord3iv"
  , "TexCoord3fv"
  , "TexCoord3dv"
  , "TexCoord4sv"
  , "TexCoord4iv"
  , "TexCoord4fv"
  , "TexCoord4dv"

  , "MultiTexCoord1s"
  , "MultiTexCoord1i"
  , "MultiTexCoord1f"
  , "MultiTexCoord1d"
  , "MultiTexCoord2s"
  , "MultiTexCoord2i"
  , "MultiTexCoord2f"
  , "MultiTexCoord2d"
  , "MultiTexCoord3s"
  , "MultiTexCoord3i"
  , "MultiTexCoord3f"
  , "MultiTexCoord3d"
  , "MultiTexCoord4s"
  , "MultiTexCoord4i"
  , "MultiTexCoord4f"
  , "MultiTexCoord4d"
  , "MultiTexCoord1sv"
  , "MultiTexCoord1iv"
  , "MultiTexCoord1fv"
  , "MultiTexCoord1dv"
  , "MultiTexCoord2sv"
  , "MultiTexCoord2iv"
  , "MultiTexCoord2fv"
  , "MultiTexCoord2dv"
  , "MultiTexCoord3sv"
  , "MultiTexCoord3iv"
  , "MultiTexCoord3fv"
  , "MultiTexCoord3dv"
  , "MultiTexCoord4sv"
  , "MultiTexCoord4iv"
  , "MultiTexCoord4fv"
  , "MultiTexCoord4dv"

  , "VertexAttrib1f"
  , "VertexAttrib1s"
  , "VertexAttrib1d"
  , "VertexAttrib2f"
  , "VertexAttrib2s"
  , "VertexAttrib2d"
  , "VertexAttrib3f"
  , "VertexAttrib3s"
  , "VertexAttrib3d"
  , "VertexAttrib4f"
  , "VertexAttrib4s"
  , "VertexAttrib4d"
  , "VertexAttrib4Nub"
  , "VertexAttrib1fv"
  , "VertexAttrib1sv"
  , "VertexAttrib1dv"
  , "VertexAttrib2fv"
  , "VertexAttrib2sv"
  , "VertexAttrib2dv"
  , "VertexAttrib3fv"
  , "VertexAttrib3sv"
  , "VertexAttrib3dv"
  , "VertexAttrib4fv"
  , "VertexAttrib4sv"
  , "VertexAttrib4dv"
  , "VertexAttrib4iv"
  , "VertexAttrib4bv"
  , "VertexAttrib4ubv"
  , "VertexAttrib4usv"
  , "VertexAttrib4uiv"
  , "VertexAttrib4Nbv"
  , "VertexAttrib4Nsv"
  , "VertexAttrib4Niv"
  , "VertexAttrib4Nubv"
  , "VertexAttrib4Nusv"
  , "VertexAttrib4Nuiv"

  , "EvalCoord1f"
  , "EvalCoord1d"
  , "EvalCoord2f"
  , "EvalCoord2d"
  , "EvalCoord1fv"
  , "EvalCoord1dv"
  , "EvalCoord2fv"
  , "EvalCoord2dv"

  , "EvalPoint1"
  , "EvalPoint2"

  , "ArrayElement"

  , "Materialf"
  , "Materiali"
  , "Materialfv"
  , "Materialiv"

  , "EdgeFlag"
  , "EdgeFlagv"

  , "CallList"

  , "CallLists"

  -- may or may not generate an error if called between Begin/End

  , "EnableClientState"

  , "EdgeFlagPointer"

  , "FogCoordPointer"

  , "TexCoordPointer"

  , "ColorPointer"

  , "SecondaryColorPointer"

  , "IndexPointer"

  , "NormalPointer"

  , "VertexPointer"

  , "VertexAttribPointer"

  , "InterleavedArrays"

  , "PixelStoref"
  , "PixelStorei"
  ]

